### ISSUE TITLE
CS Set incorrectly when running code

### ISSUE THREAD

**Issue by bibble235** [thelastoutpostworkshop/ESP32LCDRound240x240Eyes#1]
Hi,

Maybe me but here goes.

The value CS is  -1 from config.h
`
#define TFT1_CS -1 //15         // TFT 1 chip select pin (set to -1 to use TFT_eSPI setup)
`

This cause the serial monitor to give out
`
 gpio_set_level(226): GPIO output gpio_num error
`

In abundance. Don't think my TFT_eSPI config is wrong but you never know.  Anyway hard coding this to 15 fixes the issue.

**Comment by thelastoutpostworkshop** [comment]
Hi,
Yes you can put your pin definitions in the config file or in your code.
If you put it in your code, you have to comment out all CS definitions in
the config file.
